/* Source: 오사카_3박4일_최종_여행가이드_Codex용.xlsx + 오사카_여행_Google_Maps_데이터_Codex용.md */
(function(){
  const place=(name,status,search,directions,note="")=>({name,status,search,directions,note});
  const P={
    hotel:place("호텔 아시아토 난바 — HOTEL ASIATO Namba","fixed","https://www.google.com/maps/search/?api=1&query=HOTEL%20ASIATO%20Namba%2C%20Osaka","https://www.google.com/maps/dir/?api=1&destination=HOTEL%20ASIATO%20Namba%2C%20Osaka","숙소. 닛폰바시·난바 도보권."),
    kix:place("간사이국제공항 제1터미널 — Kansai International Airport Terminal 1","fixed","https://www.google.com/maps/search/?api=1&query=Kansai%20International%20Airport%20Terminal%201","https://www.google.com/maps/dir/?api=1&destination=Kansai%20International%20Airport%20Terminal%201","TW319 도착 및 TW322 출발 터미널."),
    nankai:place("난카이 난바역 — 南海なんば駅","fixed","https://www.google.com/maps/search/?api=1&query=Nankai%20Namba%20Station","https://www.google.com/maps/dir/?api=1&destination=Nankai%20Namba%20Station","오사카 메트로 난바역과 혼동하지 않는다."),
    miyamoto:place("미야모토 무나시 난바권 지점 — 宮本むなし なんば","branch_to_verify","https://www.google.com/maps/search/?api=1&query=%E5%AE%AE%E6%9C%AC%E3%82%80%E3%81%AA%E3%81%97%20%E3%81%AA%E3%82%93%E3%81%B0%20%E5%A4%A7%E9%98%AA","https://www.google.com/maps/dir/?api=1&destination=%E5%AE%AE%E6%9C%AC%E3%82%80%E3%81%AA%E3%81%97%20%E3%81%AA%E3%82%93%E3%81%B0%20%E5%A4%A7%E9%98%AA","정확한 지점·영업 여부는 출발 전 재확인."),
    marufuku:place("마루후쿠커피 본점 — 丸福珈琲店 千日前本店","fixed","https://www.google.com/maps/search/?api=1&query=%E4%B8%B8%E7%A6%8F%E7%8F%88%E7%90%B2%E5%BA%97%20%E5%8D%83%E6%97%A5%E5%89%8D%E6%9C%AC%E5%BA%97","https://www.google.com/maps/dir/?api=1&destination=%E4%B8%B8%E7%A6%8F%E7%8F%88%E7%90%B2%E5%BA%97%20%E5%8D%83%E6%97%A5%E5%89%8D%E6%9C%AC%E5%BA%97","오래된 킷사텐. 커피·디저트 후보."),
    nambaWalk:place("난바워크 — なんばウォーク","fixed_area","https://www.google.com/maps/search/?api=1&query=%E3%81%AA%E3%82%93%E3%81%B0%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%AF","https://www.google.com/maps/dir/?api=1&destination=%E3%81%AA%E3%82%93%E3%81%B0%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%AF","더운 시간대 실내 산책·쇼핑 구역."),
    donki:place("돈키호테 난바 센니치마에점 — ドン・キホーテ なんば千日前店","fixed","https://www.google.com/maps/search/?api=1&query=%E3%83%89%E3%83%B3%E3%83%BB%E3%82%AD%E3%83%9B%E3%83%BC%E3%83%86%20%E3%81%AA%E3%82%93%E3%81%B0%E5%8D%83%E6%97%A5%E5%89%8D%E5%BA%97","https://www.google.com/maps/dir/?api=1&destination=%E3%83%89%E3%83%B3%E3%83%BB%E3%82%AD%E3%83%9B%E3%83%BC%E3%83%86%20%E3%81%AA%E3%82%93%E3%81%B0%E5%8D%83%E6%97%A5%E5%89%8D%E5%BA%97"),
    fukutaro:place("후쿠타로 본점 — 福太郎 本店","fixed","https://www.google.com/maps/search/?api=1&query=%E7%A6%8F%E5%A4%AA%E9%83%8E%20%E6%9C%AC%E5%BA%97%20%E5%A4%A7%E9%98%AA","https://www.google.com/maps/dir/?api=1&destination=%E7%A6%8F%E5%A4%AA%E9%83%8E%20%E6%9C%AC%E5%BA%97%20%E5%A4%A7%E9%98%AA","오코노미야키 저녁."),
    glico:place("도톤보리 글리코사인 — Dotonbori Glico Sign","fixed","https://www.google.com/maps/search/?api=1&query=Dotonbori%20Glico%20Sign","https://www.google.com/maps/dir/?api=1&destination=Dotonbori%20Glico%20Sign","도톤보리 야경 핵심 지점."),
    yayoiken:place("야요이켄 닛폰바시점 — やよい軒 日本橋店","fixed","https://www.google.com/maps/search/?api=1&query=%E3%82%84%E3%82%88%E3%81%84%E8%BB%92%20%E6%97%A5%E6%9C%AC%E6%A9%8B%E5%BA%97%20%E5%A4%A7%E9%98%AA","https://www.google.com/maps/dir/?api=1&destination=%E3%82%84%E3%82%88%E3%81%84%E8%BB%92%20%E6%97%A5%E6%9C%AC%E6%A9%8B%E5%BA%97%20%E5%A4%A7%E9%98%AA","교토 출발 전 일본식 조식."),
    kiyomizu:place("기요미즈데라 — 清水寺","fixed","https://www.google.com/maps/search/?api=1&query=%E6%B8%85%E6%B0%B4%E5%AF%BA%20%E4%BA%AC%E9%83%BD","https://www.google.com/maps/dir/?api=1&destination=%E6%B8%85%E6%B0%B4%E5%AF%BA%20%E4%BA%AC%E9%83%BD","본당·무대·오토와폭포. 특별내진은 현장 선택."),
    kamanza:place("니넨자카 가마자 — 二年坂 釜座 KAMANZA","fixed","https://www.google.com/maps/search/?api=1&query=%E4%BA%8C%E5%B9%B4%E5%9D%82%20%E9%87%9C%E5%BA%A7%20KAMANZA%20%E4%BA%AC%E9%83%BD","https://www.google.com/maps/dir/?api=1&destination=%E4%BA%8C%E5%B9%B4%E5%9D%82%20%E9%87%9C%E5%BA%A7%20KAMANZA%20%E4%BA%AC%E9%83%BD","유바·나마후·두부 중심 교토식 점심."),
    yasaka:place("야사카신사 — 八坂神社","fixed","https://www.google.com/maps/search/?api=1&query=%E5%85%AB%E5%9D%82%E7%A5%9E%E7%A4%BE%20%E4%BA%AC%E9%83%BD","https://www.google.com/maps/dir/?api=1&destination=%E5%85%AB%E5%9D%82%E7%A5%9E%E7%A4%BE%20%E4%BA%AC%E9%83%BD"),
    gyukatsu:place("규카츠 교토카츠규 아베노 신주쿠고치소빌점 — 牛カツ京都勝牛 あべの新宿ごちそうビル店","fixed","https://www.google.com/maps/search/?api=1&query=%E7%89%9B%E3%82%AB%E3%83%84%E4%BA%AC%E9%83%BD%E5%8B%9D%E7%89%9B%20%E3%81%82%E3%81%B9%E3%81%AE%E6%96%B0%E5%AE%BF%E3%81%94%E3%81%A1%E3%81%9D%E3%81%86%E3%83%93%E3%83%AB%E5%BA%97","https://www.google.com/maps/dir/?api=1&destination=%E7%89%9B%E3%82%AB%E3%83%84%E4%BA%AC%E9%83%BD%E5%8B%9D%E7%89%9B%20%E3%81%82%E3%81%B9%E3%81%AE%E6%96%B0%E5%AE%BF%E3%81%94%E3%81%A1%E3%81%9D%E3%81%86%E3%83%93%E3%83%AB%E5%BA%97","대기 30분 이상이면 인근 식당으로 전환."),
    tsutenkaku:place("츠텐카쿠 — 通天閣","exterior_fixed_observatory_optional","https://www.google.com/maps/search/?api=1&query=%E9%80%9A%E5%A4%A9%E9%96%A3%20%E5%A4%A7%E9%98%AA","https://www.google.com/maps/dir/?api=1&destination=%E9%80%9A%E5%A4%A9%E9%96%A3%20%E5%A4%A7%E9%98%AA","외관 관람 기본. 전망대는 대기가 거의 없을 때만."),
    ibuki:place("이부키커피 구로몬시장점 — 伊吹珈琲店 黒門市場","fixed","https://www.google.com/maps/search/?api=1&query=%E4%BC%8A%E5%90%B9%E7%8F%88%E7%90%B2%E5%BA%97%20%E9%BB%92%E9%96%80%E5%B8%82%E5%A0%B4","https://www.google.com/maps/dir/?api=1&destination=%E4%BC%8A%E5%90%B9%E7%8F%88%E7%90%B2%E5%BA%97%20%E9%BB%92%E9%96%80%E5%B8%82%E5%A0%B4"),
    tenmangu:place("오사카텐만구 — 大阪天満宮","fixed","https://www.google.com/maps/search/?api=1&query=%E5%A4%A7%E9%98%AA%E5%A4%A9%E6%BA%80%E5%AE%AE","https://www.google.com/maps/dir/?api=1&destination=%E5%A4%A7%E9%98%AA%E5%A4%A9%E6%BA%80%E5%AE%AE"),
    harukoma:place("하루코마 지점 — 春駒 支店","fixed_verify_holiday","https://www.google.com/maps/search/?api=1&query=%E6%98%A5%E9%A7%92%20%E6%94%AF%E5%BA%97%20%E5%A4%A7%E9%98%AA%20%E5%A4%A9%E6%BA%80","https://www.google.com/maps/dir/?api=1&destination=%E6%98%A5%E9%A7%92%20%E6%94%AF%E5%BA%97%20%E5%A4%A7%E9%98%AA%20%E5%A4%A9%E6%BA%80","공휴일 영업과 지점 위치 재확인."),
    pokemon:place("포켓몬센터 오사카 — Pokémon Center Osaka","fixed","https://www.google.com/maps/search/?api=1&query=Pok%C3%A9mon%20Center%20Osaka%20Daimaru%20Umeda","https://www.google.com/maps/dir/?api=1&destination=Pok%C3%A9mon%20Center%20Osaka%20Daimaru%20Umeda"),
    romantei:place("로만테이 루쿠아 오사카점 — ビフテキ重・肉飯 ロマン亭 ルクア大阪店","fixed","https://www.google.com/maps/search/?api=1&query=%E3%83%93%E3%83%95%E3%83%86%E3%82%AD%E9%87%8D%20%E8%82%89%E9%A3%AF%20%E3%83%AD%E3%83%9E%E3%83%B3%E4%BA%AD%20%E3%83%AB%E3%82%AF%E3%82%A2%E5%A4%A7%E9%98%AA%E5%BA%97","https://www.google.com/maps/dir/?api=1&destination=%E3%83%93%E3%83%95%E3%83%86%E3%82%AD%E9%87%8D%20%E8%82%89%E9%A3%AF%20%E3%83%AD%E3%83%9E%E3%83%B3%E4%BA%AD%20%E3%83%AB%E3%82%AF%E3%82%A2%E5%A4%A7%E9%98%AA%E5%BA%97"),
    bakery:place("더 시티 베이커리 그랜드 프런트 오사카 — THE CITY BAKERY Grand Front Osaka","fixed","https://www.google.com/maps/search/?api=1&query=THE%20CITY%20BAKERY%20Grand%20Front%20Osaka","https://www.google.com/maps/dir/?api=1&destination=THE%20CITY%20BAKERY%20Grand%20Front%20Osaka"),
    sky:place("우메다 스카이빌딩 공중정원 — Kuchu Teien Observatory","fixed_verify_hours","https://www.google.com/maps/search/?api=1&query=Kuchu%20Teien%20Observatory%20Osaka","https://www.google.com/maps/dir/?api=1&destination=Kuchu%20Teien%20Observatory%20Osaka","입장 마감·티켓 정책은 출발 전 재확인."),
    shinpachi:place("신파치식당 오사카닛폰바시점 — しんぱち食堂 大阪日本橋店","fixed","https://www.google.com/maps/search/?api=1&query=%E3%81%97%E3%82%93%E3%81%B1%E3%81%A1%E9%A3%9F%E5%A0%82%20%E5%A4%A7%E9%98%AA%E6%97%A5%E6%9C%AC%E6%A9%8B%E5%BA%97","https://www.google.com/maps/dir/?api=1&destination=%E3%81%97%E3%82%93%E3%81%B1%E3%81%A1%E9%A3%9F%E5%A0%82%20%E5%A4%A7%E9%98%AA%E6%97%A5%E6%9C%AC%E6%A9%8B%E5%BA%97")
  };
  const route=(url,note,steps=[])=>({url,note,steps});
  const R={
    d1airport:route("https://www.google.com/maps/dir/?api=1&origin=Kansai%20International%20Airport%20Terminal%201&destination=Nankai%20Namba%20Station&travelmode=transit","공항 → 난카이 난바역",["간사이공항역에서 라피트 또는 공항급행 선택","라피트는 지정석, 공항급행은 자유석","피로도와 먼저 출발하는 편을 보고 결정"]),
    d2kyoto:route("https://www.google.com/maps/dir/?api=1&origin=%E6%97%A5%E6%9C%AC%E6%A9%8B%E9%A7%85%20%E5%A4%A7%E9%98%AA&destination=%E6%B8%85%E6%B0%B4%E4%BA%94%E6%9D%A1%E9%A7%85%20%E4%BA%AC%E9%83%BD&travelmode=transit","닛폰바시역 → 기타하마 환승 → 기요미즈고조역",["사카이스지선 「덴진바시스지로쿠초메·기타센리 방면」으로 기타하마역 하차","게이한 본선 표지판을 따라 환승","「데마치야나기 방면」 정차 열차 탑승 — 특급은 기요미즈고조역에 서지 않음","기요미즈고조역 하차 후 고조자카 방향으로 도보"]),
    d2tennoji:route("https://www.google.com/maps/dir/?api=1&origin=%E7%A5%87%E5%9C%92%E5%9B%9B%E6%9D%A1%E9%A7%85&destination=%E7%89%9B%E3%82%AB%E3%83%84%E4%BA%AC%E9%83%BD%E5%8B%9D%E7%89%9B%20%E3%81%82%E3%81%B9%E3%81%AE%E6%96%B0%E5%AE%BF%E3%81%94%E3%81%A1%E3%81%9D%E3%81%86%E3%83%93%E3%83%AB%E5%BA%97&travelmode=transit","기온시조역 → 기타하마 환승 → 덴노지",["기온시조역에서 「淀屋橋・中之島方面」 게이한선 탑승","기타하마역 하차 후 Osaka Metro 堺筋線 표지판을 따라 환승","사카이스지선 「天下茶屋方面」 덴가차야 방면 탑승","동물원앞역에서 미도스지선 환승 후 덴노지역 1정거장","아베노·긴테쓰 방면 표지판을 따라 식당 이동"]),
    d3tenma:route("https://www.google.com/maps/dir/?api=1&origin=%E6%97%A5%E6%9C%AC%E6%A9%8B%E9%A7%85%20%E5%A4%A7%E9%98%AA&destination=%E5%A4%A7%E9%98%AA%E5%A4%A9%E6%BA%80%E5%AE%AE&travelmode=transit","닛폰바시역 → 미나미모리마치역 → 오사카텐만구",["사카이스지선 「기타센리·덴진바시스지로쿠초메 방면」 탑승","미나미모리마치역 하차 후 오사카텐만구로 이동"]),
    d4airport:route("https://www.google.com/maps/dir/?api=1&origin=Nankai%20Namba%20Station&destination=Kansai%20International%20Airport%20Terminal%201&travelmode=transit","라피트 권장: 난카이 난바역 → 간사이공항 T1",["Google Maps 목적지를 Nankai Namba Station으로 설정","「南海電車 / NANKAI」「関西空港」 표지판을 따라 3층 개찰구로 이동","라피트 승차권+특급권과 좌석 번호 확인","전광판의 Rapi:t·플랫폼·출발 시각 재확인","간사이공항역 도착 후 T1 국제선 출발층으로 이동"])
  };
  const s=(t,title,intro,placeKey=null,routeKey=null,extra={})=>({t,title,cat:extra.cat||"일정",compact:{summary:intro},detail:{intro,primary:extra.tips||[],recommendation:[],info:extra.info||[],costLine:"",reserveNote:extra.caution||"",alternative:extra.alternative||""},place:placeKey?P[placeKey]:null,route:routeKey?R[routeKey]:null});
  window.TRAVEL_GUIDE={
    days:{
      "1일차":{date:"2026-08-09",theme:"난바·도톤보리",foods:"도착·난바 적응·도톤보리 야경",stops:[s("09:20","부산 출발","티웨이항공 TW319 탑승. Visit Japan Web·여권·숙소 주소를 준비.",null,null,{cat:"이동"}),s("10:55","간사이공항 T1 도착","입국심사·수하물 수령 후 난카이 전철 표지판을 따라 이동.","kix","d1airport",{cat:"이동"}),s("12:00 전후","간사이공항역 → 난카이 난바역","라피트 또는 공항급행 이용.","nankai","d1airport",{cat:"이동",caution:"정확한 운행 시각은 출발 직전 재확인."}),s("13:00 전후","숙소 이동·짐 보관","난카이 난바역에서 도보 약 10분. 프런트에 짐 보관.","hotel",null,{cat:"일정"}),s("13:20","미야모토 무나시","일본식 정식으로 늦은 점심.","miyamoto",null,{caution:"지점·영업 여부를 출발 전 재확인."}),s("14:20","마루후쿠커피 본점","오래된 킷사텐 커피와 디저트.","marufuku"),s("15:10","난바워크·센니치마에 산책","지하상가·숙소 주변을 천천히 둘러봄.","nambaWalk",null,{alternative:"더우면 실내 중심으로 이동."}),s("16:00","호텔 체크인·휴식","샤워·냉방·충전 후 저녁 전 확실히 휴식.","hotel"),s("18:00","돈키호테 난바 센니치마에점","생필품 위주로 구매.","donki"),s("19:30","후쿠타로 본점","오코노미야키 저녁.","fukutaro",null,{alternative:"대기가 길면 주변을 잠시 구경하고 무리한 우회는 하지 않음."}),s("21:00","도톤보리 글리코사인","글리코사인·강변 야경 후 숙소 복귀.","glico"),s("22:00 이후","숙소","가벼운 음료·야식을 선택하고 다음 날 교토 출발을 위해 일찍 마무리.","hotel")]},
      "2일차":{date:"2026-08-10",theme:"교토·신세카이",foods:"교토 관광·규카츠·신세카이",stops:[s("07:00","기상·준비","물·손수건·휴대용 선풍기·자외선 차단제 준비."),s("07:30","야요이켄 닛폰바시점","일본식 조식. 너무 과식하지 않음.","yayoiken"),s("08:10","닛폰바시역 → 기타하마역","사카이스지선 이동 후 게이한선 환승.",null,"d2kyoto",{cat:"이동"}),s("09:15 전후","기요미즈고조역","하차 후 고조자카 방향. 음료 먼저 구매.",null,"d2kyoto",{cat:"이동"}),s("09:20~10:00","고조자카 → 기요미즈자카","오르막을 천천히 이동.","kiyomizu", "d2kyoto",{cat:"이동"}),s("10:00~11:20","기요미즈데라","벤케이 석장·게타 체험 → 본당·무대 → 오토와폭포.","kiyomizu",null,{alternative:"특별내진은 더위·혼잡·체력을 보고 선택."}),s("11:20~12:10","산넨자카·니넨자카","전통 거리와 상점 구경. 군것질은 하나만 선택.",null,null,{cat:"일정"}),s("12:10 전후","니넨자카 가마자","유바·나마후·두부 중심 점심.","kamanza",null,{alternative:"대기가 길면 인근 유사 메뉴 식당으로 전환."}),s("13:10","니넨자카·고다이지 주변","말차 아이스크림·당고·야쓰하시 중 하나 선택."),s("13:50","야사카신사","경내 핵심 구간 관람 후 기온 방향으로 이동.","yasaka"),s("14:20~15:20","기온 산책","하나미코지·기온 시라카와 산책.",null,null,{alternative:"폭염이면 가와라마치 실내 카페·상점에서 20~30분 휴식."}),s("15:30 전후","기온시조역 출발","교토에서 덴노지로 이동.",null,"d2tennoji",{cat:"이동"}),s("16:40~17:00","교토카츠규 아베노점","규카츠 이른 저녁.","gyukatsu","d2tennoji",{alternative:"대기 30분 이상이면 같은 건물·덴노지역 인근 식당."}),s("18:00~18:40","신세카이 핵심 구간","아베노 보행육교 → 잔잔요코초 → 츠텐카쿠 외관 → 신세카이 혼도리.","tsutenkaku",null,{alternative:"전망대는 대기가 거의 없을 때만."}),s("19:00","에비스초역 → 닛폰바시역","사카이스지선으로 환승 없이 이동.",null,null,{cat:"이동"}),s("19:30~21:00","난바·신사이바시 자유 쇼핑","품목은 현장에서 자유 결정."),s("21:00 이후","숙소 짐 보관 후 술자리","현장 상황에 따라 이자카야 또는 숙소 야식 선택.","hotel",null,{alternative:"우오야 히데조 별관 → 만석이면 토코하 → 모두 어려우면 구로몬 나카가와 숙소 야식."})]},
      "3일차":{date:"2026-08-11",theme:"텐마·우메다",foods:"스시·우메다 실내 일정·야경",stops:[s("08:00","이부키커피 구로몬시장점","커피와 토스트·모닝 메뉴.","ibuki"),s("09:00","닛폰바시역 → 미나미모리마치역","사카이스지선으로 이동.",null,"d3tenma",{cat:"이동"}),s("09:30","오사카텐만구","경내를 천천히 둘러봄.","tenmangu"),s("10:10","텐진바시스지상점가","남쪽에서 북쪽으로 식당까지 자연스럽게 이동."),s("11:00","하루코마 지점","스시 첫 타임 목표.","harukoma",null,{alternative:"줄이 지나치게 길면 주변 초밥집으로 전환."}),s("12:20","우메다 이동","덴마역 또는 오기마치역에서 우메다·오사카역 방면 이동.",null,null,{cat:"이동"}),s("13:00~16:30","오사카역 쇼핑·실내 관광","포켓몬센터 → LUCUA → 닌텐도 오사카·가챠 매장.","pokemon",null,{alternative:"더운 시간은 실내에서 보냄."}),s("16:40","로만테이 루쿠아 오사카점","비프테키주·니쿠메시 이른 저녁.","romantei"),s("18:00","더 시티 베이커리","커피·오늘의 디저트 휴식.","bakery"),s("19:10","그랜드 프런트·우메키타 산책","스카이빌딩 방향으로 천천히 이동."),s("20:10~21:20","우메다 스카이빌딩 공중정원","야경 감상.","sky",null,{alternative:"HEP FIVE는 시간·체력이 남을 때만 외관·쇼핑 선택."}),s("21:30 이후","자유 일정·숙소 복귀","오사카역에서 미도스지선 또는 택시로 숙소 복귀.","hotel",null,{alternative:"야식은 배고픔에 따라 자유 선택."})]},
      "4일차":{date:"2026-08-12",theme:"귀국",foods:"조식·라피트·공항 수속",stops:[s("07:30","기상·짐 1차 정리","액체류·면세품·보조배터리 위치 확인."),s("08:00","신파치식당 오사카닛폰바시점","구운 생선 또는 고기 정식 조식.","shinpachi"),s("09:00","숙소 복귀","샤워·충전·캐리어 최종 정리.","hotel"),s("10:40","체크아웃","기본 체크아웃 11:00. 예약 플랜 조건 재확인.","hotel"),s("10:50~11:10","호텔 → 난카이 난바역","캐리어로 도보 약 10분.","nankai","d4airport",{cat:"이동"}),s("11:30 전후","난카이 난바역 → 간사이공항역","라피트 지정석 이용 권장.","nankai","d4airport",{cat:"이동",caution:"정확한 운행 시각은 출발 직전 공식 시간표 재확인."}),s("12:10~12:25","간사이공항 T1 도착","역에서 국제선 출발층으로 이동.","kix","d4airport",{cat:"이동"}),s("12:30~13:20","체크인·수하물 위탁·출국 수속","항공사 카운터 → 수하물 위탁 → 보안검색 → 출국심사.","kix",null,{caution:"혼잡하면 점심보다 수속 우선."}),s("13:20~14:20","면세구역 점심·쇼핑","줄이 짧은 라멘·스시·일식 중 현장 선택.","kix",null,{alternative:"특정 식당을 고정하지 않고 탑승구 위치·대기열 우선."}),s("14:20","탑승구 이동","셔틀 구역 여부를 확인하고 출발 50~60분 전 게이트 주변 도착.","kix"),s("15:30","간사이공항 출발","티웨이항공 TW322.","kix",null,{cat:"이동"}),s("17:05","부산 도착","입국·수하물 수령 후 귀가.",null,null,{cat:"이동"})]}
    },
    alternatives:["생선관 구로몬 나카가와 — 生鮮館 黒門中川: 숙소 야식 대안","우오야 히데조 별관 — 魚屋ひでぞう 別館: 2일차 밤 현장 확인 1순위","숯불 야키토리 토코하 난바점 — 炭火焼鳥 とこ葉 なんば店: 히데조 만석 시 2순위","기요미즈데라 천일참배 특별내진 공개: 더위·혼잡·체력에 따라 선택","츠텐카쿠 전망대·HEP FIVE: 대기·시간·체력이 남을 때만 선택"]
  };
  const day2=window.TRAVEL_GUIDE.days["2일차"];
  day2.stops.splice(3,0,s("08:25","기타하마역 환승","게이한 본선 표지판을 따라 이동. 데마치야나기 방면 열차 탑승. 특급은 기요미즈고조역에 서지 않으므로 준급·보통 등 정차 열차를 확인.",null,"d2kyoto",{cat:"이동"}));
  const excelDetails={
    "1일차":["티웨이항공 TW319 탑승. 기내에서 Visit Japan Web, 여권, 숙소 주소를 바로 꺼낼 수 있게 준비.","입국심사·수하물 수령 후 난카이 전철 표지판을 따라 간사이공항역으로 이동.","라피트 또는 공항급행 이용. 라피트는 지정석, 공항급행은 자유석. 당일 먼저 출발하는 편과 피로도를 보고 결정.","난카이 난바역에서 숙소까지 도보 약 10분. 호텔 아시아토 난바 프런트에 짐을 맡긴다.","숙소·난바 주변 지점에서 일본식 정식으로 늦은 점심. 정확한 지점은 출발 직전 영업 여부를 확인.","오사카의 오래된 킷사텐 분위기와 커피를 즐긴다. 오늘의 디저트 1회도 여기서 해결 가능.","지하상가와 숙소 주변을 천천히 둘러본다. 더우면 실내 중심으로 이동.","샤워·냉방·충전. 저녁 전 1시간 이상 확실히 쉰다.","여행 중 필요한 생필품 위주로 먼저 구매. 선물 쇼핑은 2일차 자유시간에 해도 된다.","오코노미야키 저녁. 대기가 길면 주변에서 잠시 구경하되, 무리한 우회는 하지 않는다.","글리코사인과 도톤보리 강변 야경을 보고 숙소로 복귀.","편의점 또는 생선관 구로몬 나카가와에서 가벼운 음료·야식 선택. 다음 날 교토 출발을 위해 일찍 마무리."],
    "2일차":["폭염 대비 물, 손수건, 휴대용 선풍기, 자외선 차단제 준비.","생선·고기·계란 등 원하는 일본식 조식을 선택. 너무 과식하지 않는다.","오사카 메트로 사카이스지선에서 덴진바시스지로쿠초메·기타센리 방면을 확인하고 기타하마역 하차.","게이한 본선 표지판을 따라 이동. 데마치야나기 방면 열차 탑승. 특급은 기요미즈고조역에 서지 않으므로 준급·보통 등 정차 열차를 확인.","하차 후 고조자카 방향으로 걷는다. 아래쪽 편의점이나 자판기에서 먼저 음료 구매.","五条坂 → 清水坂. 오르막이지만 상점과 거리 풍경을 보며 천천히 이동.","입구 근처 벤케이의 석장과 철제 게타 체험 → 본당·무대 → 오토와폭포. 천일참배 특별내진 공개는 더위·혼잡·체력을 보고 선택.","産寧坂（三年坂）→ 二年坂. 전통 거리와 상점 구경. 군것질은 점심 후 하나만 선택.","유바·나마후·두부 등 교토식 점심. 대기가 길면 인근 유사 메뉴 식당으로 전환.","말차 아이스크림·당고·야쓰하시 중 하나만 선택. 동행은 음료나 짭짤한 간식으로 대체. 고다이지 내부 관람은 생략.","경내 핵심 구간을 둘러보고 기온 방향으로 이동.","하나미코지 — 花見小路通 → 기온 시라카와 — 祇園白川. 날씨가 매우 더우면 가와라마치 실내 카페·상점에서 휴식.","게이한 본선 요도야바시 방면 탑승 → 기타하마역 하차 → 오사카 메트로 사카이스지선 덴가차야 방면 환승 → 덴노지 이동은 아래 상세 교통 안내 참고.","규카츠 이른 저녁. 대기 20분 이내면 이용, 30분 이상이면 같은 건물·덴노지역 인근 식당으로 전환.","아베노 보행육교 → 잔잔요코초 — ジャンジャン横丁 → 츠텐카쿠 외관 — 通天閣 → 신세카이 혼도리. 전망대는 대기가 거의 없을 때만 선택.","오사카 메트로 사카이스지선 기타센리·덴진바시스지로쿠초메 방면. 닛폰바시역까지 환승 없이 이동.","품목은 현장에서 자유롭게 결정. 무거운 물건을 너무 많이 사지 않는다.","1순위 우오야 히데조 별관 — 魚屋ひでぞう 別館 현장 확인 → 만석이면 숯불 야키토리 토코하 난바점 — 炭火焼鳥 とこ葉 なんば店. 둘 다 어려우면 생선관 구로몬 나카가와에서 회·초밥·술을 사서 숙소 야식."],
    "3일차":["오사카식 킷사텐 아침. 커피와 토스트·모닝 메뉴로 시작.","사카이스지선 기타센리·덴진바시스지로쿠초메 방면. 미나미모리마치역 하차.","경내를 천천히 둘러본다.","남쪽에서 북쪽 방향으로 상점가를 구경. 전 구간 완주가 목적이 아니라 식당까지 자연스럽게 이동.","스시 첫 타임 목표. 공휴일 영업과 지점 위치는 출발 직전 재확인. 줄이 지나치게 길면 주변 초밥집으로 전환.","덴마역 또는 오기마치역에서 우메다·오사카역 방면 이동.","포켓몬센터 오사카 — Pokémon Center Osaka → LUCUA Osaka → 닌텐도 오사카·가챠 매장. 더운 시간은 실내에서 보낸다.","비프테키주·니쿠메시 이른 저녁.","커피와 오늘의 디저트. 동행은 커피나 짭짤한 베이커리 메뉴 선택.","스카이빌딩 방향으로 천천히 이동. 피곤하면 실내에서 더 쉬었다가 출발.","야경 감상. 입장 마감·티켓 정책은 출발 직전 확인. HEP FIVE는 시간과 체력이 남을 때만 외관·쇼핑 정도로 선택.","오사카역에서 미도스지선 또는 택시로 숙소 복귀. 야식은 배고픔에 따라 자유 선택."],
    "4일차":["액체류·면세품·보조배터리 위치를 확인. 보조배터리는 위탁수하물에 넣지 않는다.","구운 생선 또는 고기 정식으로 든든하게 아침 식사.","샤워·충전·캐리어 최종 정리. 객실 냉장고와 콘센트, 침대 아래를 확인.","호텔 기본 체크아웃은 11:00. 예약 플랜에 별도 조건이 없는지 예약서에서 확인.","캐리어를 끌고 도보 약 10분. 난카이 전철 「関西空港」 표지판을 따라 3층 개찰구·특급 승차 구역으로 이동.","라피트 지정석 이용 권장. 정확한 2026년 8월 12일 운행 시각은 출발 직전 공식 시간표에서 재확인.","역에서 제1터미널 국제선 출발층으로 이동. 역에서 체크인 구역까지 도보 약 10분을 감안.","항공사 카운터 확인 → 수하물 위탁 → 보안검색 → 출국심사. 혼잡하면 점심 시간을 줄이고 수속을 우선.","특정 식당은 고정하지 않는다. 가까운 라멘·스시·일식 중 줄이 짧은 곳에서 식사 후 면세점 구경.","탑승구가 셔틀 구역인지 확인하고 늦어도 출발 50~60분 전에는 게이트 주변 도착.","티웨이항공 TW322.","입국·수하물 수령 후 귀가."]
  };
  Object.entries(excelDetails).forEach(([day,details])=>window.TRAVEL_GUIDE.days[day].stops.forEach((stop,index)=>{const full=details[index];if(!full)return;stop.detail.intro=full;}));
})();
/* Day 2 rainy-day Plan B. Kept separate from the confirmed Kyoto timetable. */
(()=>{
  const guide=window.TRAVEL_GUIDE;
  if(!guide)return;
  const maps=(name,nameJa,searchName,address,note="")=>{const query=encodeURIComponent(searchName);return{name:`${name} — ${nameJa} · ${searchName}`,status:"rain_plan",search:`https://www.google.com/maps/search/?api=1&query=${query}`,directions:`https://www.google.com/maps/dir/?api=1&destination=${query}`,note:`${address}${note?` · ${note}`:""}`}};
  const route=(destination,note,steps=[])=>({url:`https://www.google.com/maps/dir/?api=1&origin=HOTEL%20ASIATO%20Namba%2C%20Osaka&destination=${encodeURIComponent(destination)}&travelmode=transit`,note,steps});
  const stop=(t,title,intro,place=null,travel=null,extra={})=>({t,title,cat:extra.cat||"우천 플랜",compact:{summary:intro},detail:{intro,primary:extra.tips||[],recommendation:[],info:extra.info||[],costLine:"",reserveNote:extra.caution||"",alternative:extra.alternative||""},place,route:travel});
  const hotel=maps("HOTEL ASIATO Namba","","HOTEL ASIATO Namba","2-10-2 Nipponbashi, Chuo Ward, Osaka, 542-0073, Japan");
  const kaiyukan=maps("가이유칸","海遊館","Osaka Aquarium Kaiyukan","1-1-10 Kaigandori, Minato Ward, Osaka, 552-0022, Japan");
  const tempozan=maps("텐포잔 마켓플레이스","天保山マーケットプレース","Tempozan Marketplace","1-1-10 Kaigandori, Minato Ward, Osaka, 552-0022, Japan");
  const solaniwa=maps("소라니와 온천","空庭温泉 OSAKA BAY TOWER","Solaniwa Onsen OSAKA BAY TOWER","1-2-3 Benten, Minato Ward, Osaka, 552-0007, Japan");
  const hips=maps("namBa HIPS","namBa HIPS","namBa HIPS","1-8-16 Namba, Chuo Ward, Osaka, 542-0076, Japan","빠칭코 체험");
  guide.rainPlan={theme:"우천 플랜 B",stops:[
    stop("09:00 전후","호텔 출발 → 가이유칸","난바역에서 Osaka Metro를 이용해 가이유칸으로 이동.",hotel,route("Osaka Aquarium Kaiyukan","난바역 → 미도스지선 → 혼마치역 환승 → 주오선 오사카코역",["오사카코역 1번 출구 이용","가이유칸까지 도보 약 5분","실제 열차 시간과 최적 경로는 당일 Google Maps 사용"]),{cat:"이동"}),
    stop("10:00~13:00","가이유칸","폭우에도 진행 가능한 실내 메인 관광지. 메인 수조 중심으로 천천히 관람.",kaiyukan,null,{tips:["예상 체류 약 2시간 30분~3시간","당일 입장권·지정시간이 필요하면 실제 방문 전 확인","혼잡하면 관람 시간이 길어질 수 있음"]}),
    stop("13:00~14:00","텐포잔 마켓플레이스 점심","가이유칸 인접 실내 공간에서 당일 원하는 메뉴를 선택.",tempozan,null,{tips:["폭우 상황에서 외부 이동 최소화","가이유칸 직후 식사와 휴식"]}),
    stop("14:00 전후","가이유칸 → 소라니와 온천","오사카코역에서 주오선으로 벤텐초역까지 환승 없이 이동.",null,{url:"https://www.google.com/maps/dir/?api=1&origin=Osakako%20Station&destination=Solaniwa%20Onsen%20OSAKA%20BAY%20TOWER&travelmode=transit",note:"오사카코역 → 주오선 → 벤텐초역",steps:["환승 없음","벤텐초역 서쪽 개찰구 → 2-A 출구","Osaka Bay Tower 연결통로 이용"]},{cat:"이동",tips:["폭우 날 외부 보행을 최소화할 수 있는 연결통로 이용"]}),
    stop("14:30~17:00 전후","소라니와 온천","관광 중 휴식과 일본식 대욕탕 체험.",solaniwa,null,{tips:["2~2.5시간을 기본 체류 시간으로 사용","유카타·목욕타월·페이스타월·기본 목욕용품 포함 안내","입장 → 유카타 → 대욕장 → 휴식 → 퇴장 순서 추천"],caution:"당일 운영·입장 가능 여부는 방문 전 확인."}),
    stop("17:00~18:00 전후","소라니와 온천 → 난바","벤텐초에서 난바 방향으로 복귀.",null,{url:"https://www.google.com/maps/dir/?api=1&origin=Solaniwa%20Onsen%20OSAKA%20BAY%20TOWER&destination=Namba%20Station&travelmode=transit",note:"벤텐초 → 난바",steps:["약 20~30분 예상","당일 Google Maps 경로 이용"]},{cat:"이동"}),
    stop("18:00 전후","namBa HIPS 빠칭코 체험","일본 빠칭코 문화를 짧게 체험하는 선택 일정.",hips,null,{tips:["30~45분만 이용","1인 최대 ¥2,000 · 추가 충전하지 않기","흥미가 없거나 혼잡하면 바로 생략"]}),
    stop("18:30 이후","난바 · 센니치마에 · 도톤보리 저녁","당일 원하는 식당을 선택하고 호텔 방향으로 자연스럽게 복귀.",hotel,null,{tips:["빠칭코 → 저녁 → 호텔 순서","비가 약하면 짧게 산책, 폭우면 바로 호텔 복귀"]})
  ]};
  const rapid=guide.days["1일차"].stops[2];
  rapid.t="12:35";rapid.compact.summary="난카이 라피트 12:35 출발. 1호차 지정석·QR 전자티켓 이용.";rapid.detail.intro="간사이공항역에서 12:35 난카이 라피트 탑승. 1호차 지정석이며 Trip.com / Linktivity QR 전자티켓은 2명 각각 사용. QR의 Use 버튼은 개찰구 앞에서 활성화.";rapid.detail.primary=["1호차 지정석","QR은 개찰구 앞에서 Use 활성화","2명 각각 별도 QR 전자티켓 사용"];
})();
